apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  namespace: default
spec:
  selector:
      matchLabels:                    # This deployment applies to the Pods matching the specified labels
        app: spring-boot
  replicas: 1
  template:
    metadata:
      name: spring-boot
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        env:
          - name: DB_SERVER
            value: mysql:3306
        image: sujjad/todo-app:v23
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  type: NordPort
  ports:
    - port: 8080
  selector:
    app: spring-boot